from os import getenv


class Config:
    SECRET_KEY = getenv('SECRET_KEY')
    SQLALCHEMY_DATABASE_URI = getenv('SQLALCHEMY_DATABASE_URI')
    SQLALCHEMY_TRACK_MODIFICATIONS = getenv("SQLALCHEMY_TRACK_MODIFICATION")
    SECURITY_PASSWORD_SALT = getenv("SECURITY_PASSWORD_SALT")
    SECURITY_PASSWORD_HASH = getenv("SECURITY_PASSWORD_HASH")
    CELERY_BROKER_URL = 'redis://redis:6379/0'
    CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
